apiVersion: batch/v1
kind: Job
metadata:
  name: spark-pi
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: spark-pi
          image: cnsnoida/test-spark:3.3.0
          command: [
            "/bin/sh",
            "-c",
            "/opt/spark/bin/spark-submit \
            --master k8s://https://10.96.0.1:443 \
            --deploy-mode cluster \
            --name spark-pi \
            --class org.apache.spark.examples.SparkPi \
            --conf spark.kubernetes.namespace=default
            --conf spark.executor.instances=2 \
            --conf spark.executor.memory=2G \
            --conf spark.executor.cores=1 \
            --conf spark.kubernetes.container.image=cnsnoida/test-spark:3.3.0 \
            --conf spark.kubernetes.container.image.pullPolicy=Always \
            --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
            --conf spark.jars.ivy=/tmp \                     
            --conf spark.kubernetes.driver.pod.name=spark-master \
            local:///opt/spark/examples/jars/spark-examples_2.12-3.3.0.jar"
          ]                 
      serviceAccountName: spark
      restartPolicy: Never
